### ISSUE TITLE
Cant login/register

### ISSUE THREAD

**Issue by mcpefirst** [flupine/VPNSox-CP#6]
After installation and import of the .sql files Im trying to access the /public folder. It gives me a "login not found on server" apache error. Cant find aany login/register files in the files either. Also when accessing the index file directly it doesnt load the CSS because it pulls the wrong path... For example /index.php/css . Please tell me if I made anything wrong. Thanks :D

**Comment by mcpefirst** [comment]
Managed to fix the issue by replacing the CSS location link.

**Comment by mcpefirst** [comment]
Now Ive got a problem after registering. After filling out all forms and then clicking on Create my Account Im getting the following:


Slim Application Error
The application could not run because of the following error:

Details
Type: Swift_TransportException
Message: Expected response code 220 but got code "", with message ""
File: /var/www/html/VPNSox-CP/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php
Line: 383

**Comment by flupine** [comment]
You need to set container.php with your own SMTP Credentials, by default is not provided with the script sorry
