### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by sp0okz** [flupine/VPNSox-CP#8]
Im getting this following error when trying to create an account

he application could not run because of the following error:

Details
Type: Swift_TransportException
Message: Expected response code 220 but got code "", with message ""
File: /var/www/html/VPNSox-CP/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php
Line: 383
Trace
#0 /var/www/html/VPNSox-CP/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(289): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('', Array)
#1 /var/www/html/VPNSox-CP/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(117): Swift_Transport_AbstractSmtpTransport->_readGreeting()
#2 /var/www/html/VPNSox-CP/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(51): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/html/VPNSox-CP/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_SendmailTransport->start()
#4 /var/www/html/VPNSox-CP/app/Controllers/RegisterController.php(52): Swift_Mailer->send(Object(Swift_Message))
#5 [internal function]: App\Controllers\RegisterController->postRegister(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#8 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/App.php(516): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /var/www/html/VPNSox-CP/app/Middlewares/PushMiddleware.php(38): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: App\Middlewares\PushMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#13 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(App\Middlewares\PushMiddleware), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#15 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#16 /var/www/html/VPNSox-CP/app/Middlewares/FlashMiddleware.php(38): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 [internal function]: App\Middlewares\FlashMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#18 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(App\Middlewares\FlashMiddleware), Array)
#19 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#20 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#21 /var/www/html/VPNSox-CP/app/Middlewares/OldMiddleware.php(38): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#22 [internal function]: App\Middlewares\OldMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#23 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(App\Middlewares\OldMiddleware), Array)
#24 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#25 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#26 /var/www/html/VPNSox-CP/app/Middlewares/TwigCsrfMiddleware.php(45): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 [internal function]: App\Middlewares\TwigCsrfMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#28 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(App\Middlewares\TwigCsrfMiddleware), Array)
#29 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#30 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#31 /var/www/html/VPNSox-CP/vendor/slim/csrf/src/Guard.php(162): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#32 [internal function]: Slim\Csrf\Guard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#33 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Slim\Csrf\Guard), Array)
#34 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#35 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#36 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#37 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/App.php(407): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#38 /var/www/html/VPNSox-CP/vendor/slim/slim/Slim/App.php(315): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#39 /var/www/html/VPNSox-CP/public/index.php(82): Slim\App->run()
#40 {main}

**Comment by ExclusiveProduction** [comment]
HEY you SPOOKZ leak me that 45$ panel from https://www.codester.com/items/6629/vpn-panel-l2tp-and-openvpn-selling-panel/   and also this source works too with a little editing

**Comment by flupine** [comment]
Issue already resolved, you need to configure smtp with your own credentials.
